# Discrete-time Markov chain

### Markov Chain : 
"A stochastic model describing a sequence of possible events in which the probability of each event depends only on the state attained in the previous event." [1]
### Discrete-time Markov chain
"A discrete-time Markov chain is a sequence of random variables X1, X2, X3, ... with the Markov property, namely that the probability of moving to the next state depends only on the present state and not on the previous states"[2]

1. https://en.oxforddictionaries.com/definition/us/markov_chain
2. [wiki](https://en.wikipedia.org/wiki/Markov_chain)

## Example

We will use first example from Takis Konstantopoulos' "One Hundred Solved Exercisesfor the subject:Stochastic Processes" [link](https://www.stat.berkeley.edu/~aldous/150/takis_exercises.pdf)

In the Dark Ages, Harvard, Dartmouth, and Yale admitted only male students. Assume that, at that time, 80 percent of the sons of Harvard men went to Harvard and the rest went to Yale, 40 percent of the sons of Yale men went to Yale, and the rest split evenly between Harvard and Dartmouth; and of the sons of Dartmouth men, 70 percent went to Dartmouth, 20 percent to Harvard, and 10 percent to Yale. (i) Find the probability that the grandson of a man from Harvard went to Harvard. (ii) Modify the above by assuming that the son of a Harvard man always went to Harvard. Again, find the probability that the grandson of a man from Harvard went to Harvard.

This is a great example to show basics of discrete-time markov chain.

## Solution

* First we show probabilities in a matrix
* Perform discrete markov chain to calculate

To calculate probability of n steps, we multiply initial state with n to the power of probability matrix(state matrix).<br>Xn = i * pow(SxS,n)

Markov chain space S = {H,D,Y} <br>
SxS= 
$\begin{pmatrix}
.8 & 0 & .2 \\
.2 & .7 & .1 \\
.3 & .3 & .4
\end{pmatrix} $

In [1]:
import numpy as np

In [2]:
SxS = np.array([[.8,0,.2],[.2,.7,.1],[.3,.3,.4]])
SxS

array([[0.8, 0. , 0.2],
       [0.2, 0.7, 0.1],
       [0.3, 0.3, 0.4]])

#### Solution of i,

To find grandson we need to calculate 2 steps from initial value which is grandfather being Harvard graduate. 

initial state = [1,0,0]

In [3]:
initial_state = np.array([[1,0,0]])
initial_state

array([[1, 0, 0]])

In [4]:
print("State matrix shape" , SxS.shape)
print("Initial state shape" , initial_state.shape)

State matrix shape (3, 3)
Initial state shape (1, 3)


In [5]:
from numpy.linalg import matrix_power

In [6]:
x =  np.matmul(initial_state,matrix_power(SxS,2))
x

array([[0.7 , 0.06, 0.24]])

Probability of grandson of the men who goes to Harvard going to Harvard is 70%

#### Solution of ii,
In this case, we turn first row of SxS to [1,0,0]. Result is obvious but lets calculate.

In [7]:
SxS[0] = np.array([1,0,0])
SxS

array([[1. , 0. , 0. ],
       [0.2, 0.7, 0.1],
       [0.3, 0.3, 0.4]])

In [8]:
x =  np.matmul(initial_state,matrix_power(SxS,2))
x

array([[1., 0., 0.]])